@echo off
echo Starting backend service...
start wsl bash -c "chmod +x /mnt/c/Users/PC/Documents/GitHub/Virtual-Cat-Companion/Main/Chatgui/start_backend.sh && /mnt/c/Users/PC/Documents/GitHub/Virtual-Cat-Companion/Main/Chatgui/start_backend.sh"
echo Starting frontend service...
start cmd /k python C:\Users\PC\Documents\GitHub\Virtual-Cat-Companion\Main\Chatgui\frontend.py